from enum import Enum

class ActionType(str, Enum):
    # Planning
    UPDATE_PLAN = "UPDATE_PLAN"
    ADVANCE_PHASE = "ADVANCE_PHASE"
    
    # Modeling
    DEFINE_VARIABLES = "DEFINE_VARIABLES"
    ADD_MODEL_CONSTRAINTS = "ADD_MODEL_CONSTRAINTS"
    REMOVE_MODEL_CONSTRAINTS = "REMOVE_MODEL_CONSTRAINTS"
    LIST_IR_SCHEMA = "LIST_IR_SCHEMA"
    SOLVE = "SOLVE"
    TEST_CONSTRAINT = "TEST_CONSTRAINT"
    FUZZ_CONSTRAINTS = "FUZZ_CONSTRAINTS"
    DECODE_SOLUTION = "DECODE_SOLUTION"
    FINISH = "FINISH"
    UPDATE_PLAN = "UPDATE_PLAN"
    REFINE_FROM_VALIDATION = "REFINE_FROM_VALIDATION"
    # Legacy
    ADD_CONSTRAINTS = "ADD_CONSTRAINTS" 
    REFINE_MODEL = "REFINE_MODEL"
