from enum import Enum

class ActionType(str, Enum):
    # Planning
    UPDATE_PLAN = "UPDATE_PLAN"
    ADVANCE_PHASE = "ADVANCE_PHASE"
    
    # Modeling
    DEFINE_VARIABLES = "DEFINE_VARIABLES"
    DEFINE_VARIABLE_PATTERN = "DEFINE_VARIABLE_PATTERN"
    ADD_MODEL_CONSTRAINTS = "ADD_MODEL_CONSTRAINTS"
    ADD_PYTHON_CONSTRAINT_BLOCK = "ADD_PYTHON_CONSTRAINT_BLOCK"
    REMOVE_MODEL_CONSTRAINTS = "REMOVE_MODEL_CONSTRAINTS"
    LIST_IR_SCHEMA = "LIST_IR_SCHEMA"
    SOLVE = "SOLVE"
    TEST_CONSTRAINT = "TEST_CONSTRAINT"
    FUZZ_CONSTRAINTS = "FUZZ_CONSTRAINTS"
    DECODE_SOLUTION = "DECODE_SOLUTION"
    FINISH = "FINISH"
    REFINE_FROM_VALIDATION = "REFINE_FROM_VALIDATION"
    # Legacy
    ADD_CONSTRAINTS = "ADD_CONSTRAINTS" 
    REFINE_MODEL = "REFINE_MODEL"
    ADD_MINIZINC_CODE = "ADD_MINIZINC_CODE"
    # File Centric
    UPDATE_MODEL_FILE = "UPDATE_MODEL_FILE"
    READ_MODEL_FILE = "READ_MODEL_FILE"
